import { DropdownTypeEnum } from "./dropdown";

// From https://www.npmjs.com/package/country-list

export type countryType = {
  iso: string
  countryName: string
  phoneCode: string
}



export const COUNTRIES = [
  { iso: "AD", countryName: "Andorra", phoneCode: "376" },
  {
    iso: "AE",
    countryName: "United Arab Emirates",
    phoneCode: "971",
  },
  {
    iso: "AF",
    countryName: "Afghanistan",
    phoneCode: "93",
  },
  {
    iso: "AG",
    countryName: "Antigua and Barbuda",
    phoneCode: "1268",
  },
  { iso: "AI", countryName: "Anguilla", phoneCode: "1264" },
  { iso: "AL", countryName: "Albania", phoneCode: "355" },
  { iso: "AM", countryName: "Armenia", phoneCode: "374" },
  { iso: "AO", countryName: "Angola", phoneCode: "244" },
  {
    iso: "AQ",
    countryName: "Antarctica",
    phoneCode: "672",
  },
  {
    iso: "AR",
    countryName: "Argentina",
    phoneCode: "54",
  },
  {
    iso: "AS",
    countryName: "American Samoa",
    phoneCode: "1684",
  },
  { iso: "AT", countryName: "Austria", phoneCode: "43" },
  { iso: "AU", countryName: "Australia", phoneCode: "61" },
  { iso: "AW", countryName: "Aruba", phoneCode: "297" },
  {
    iso: "AX",
    countryName: "Åland Islands",
    phoneCode: "358",
  },
  {
    iso: "AZ",
    countryName: "Azerbaijan",
    phoneCode: "994",
  },
  {
    iso: "BA",
    countryName: "Bosnia and Herzegovina",
    phoneCode: "387",
  },
  {
    iso: "BB",
    countryName: "Barbados",
    phoneCode: "1246",
  },
  {
    iso: "BD",
    countryName: "Bangladesh",
    phoneCode: "880",
  },
  { iso: "BE", countryName: "Belgium", phoneCode: "32" },
  {
    iso: "BF",
    countryName: "Burkina Faso",
    phoneCode: "226",
  },
  { iso: "BG", countryName: "Bulgaria", phoneCode: "359" },
  { iso: "BH", countryName: "Bahrain", phoneCode: "973" },
  { iso: "BI", countryName: "Burundi", phoneCode: "257" },
  { iso: "BJ", countryName: "Benin", phoneCode: "229" },
  {
    iso: "BL",
    countryName: "Saint Barthélemy",
    phoneCode: "590",
  },
  {
    iso: "BM",
    countryName: "Bermuda",
    phoneCode: "1441",
  },
  {
    iso: "BN",
    countryName: "Brunei Darussalam",
    phoneCode: "673",
  },
  {
    iso: "BO",
    countryName: "Bolivia, Plurinational State of",
    phoneCode: "591",
  },
  { iso: "BR", countryName: "Brazil", phoneCode: "55" },
  { iso: "BS", countryName: "Bahamas", phoneCode: "1242" },
  { iso: "BT", countryName: "Bhutan", phoneCode: "975" },
  { iso: "BW", countryName: "Botswana", phoneCode: "267" },
  { iso: "BY", countryName: "Belarus", phoneCode: "375" },
  { iso: "BZ", countryName: "Belize", phoneCode: "501" },
  { iso: "CA", countryName: "Canada", phoneCode: "1" },
  {
    iso: "CC",
    countryName: "Cocos (Keeling) Islands",
    phoneCode: "61",
  },
  {
    iso: "CD",
    countryName: "Congo, Democratic Republic of the",
    phoneCode: "243",
  },
  {
    iso: "CF",
    countryName: "Central African Republic",
    phoneCode: "236",
  },
  { iso: "CG", countryName: "Congo", phoneCode: "242" },
  { iso: "CH", countryName: "Switzerland", phoneCode: "41" },
  {
    iso: "CI",
    countryName: "Côte d'Ivoire",
    phoneCode: "225",
  },
  {
    iso: "CK",
    countryName: "Cook Islands",
    phoneCode: "682",
  },
  { iso: "CL", countryName: "Chile", phoneCode: "56" },
  {
    iso: "CM",
    countryName: "Cameroon",
    phoneCode: "237",
  },
  { iso: "CN", countryName: "China", phoneCode: "86" },
  { iso: "CO", countryName: "Colombia", phoneCode: "57" },
  {
    iso: "CR",
    countryName: "Costa Rica",
    phoneCode: "506",
  },
  { iso: "CU", countryName: "Cuba", phoneCode: "53" },
  {
    iso: "CV",
    countryName: "Cabo Verde",
    phoneCode: "238",
  },
  {
    iso: "CX",
    countryName: "Christmas Island",
    phoneCode: "61",
  },
  { iso: "CY", countryName: "Cyprus", phoneCode: "357" },
  { iso: "CZ", countryName: "Czechia", phoneCode: "420" },
  { iso: "DE", countryName: "Germany", phoneCode: "49" },
  { iso: "DJ", countryName: "Djibouti", phoneCode: "253" },
  { iso: "DK", countryName: "Denmark", phoneCode: "45" },
  {
    iso: "DM",
    countryName: "Dominica",
    phoneCode: "1767",
  },
  {
    iso: "DO",
    countryName: "Dominican Republic",
    phoneCode: "1849",
  },
  { iso: "DZ", countryName: "Algeria", phoneCode: "213" },
  { iso: "EC", countryName: "Ecuador", phoneCode: "593" },
  { iso: "EE", countryName: "Estonia", phoneCode: "372" },
  { iso: "EG", countryName: "Egypt", phoneCode: "20" },
  { iso: "ER", countryName: "Eritrea", phoneCode: "291" },
  { iso: "ES", countryName: "Spain", phoneCode: "34" },
  { iso: "ET", countryName: "Ethiopia", phoneCode: "251" },
  { iso: "FI", countryName: "Finland", phoneCode: "358" },
  { iso: "FJ", countryName: "Fiji", phoneCode: "679" },
  {
    iso: "FK",
    countryName: "Falkland Islands (Malvinas)",
    phoneCode: "500",
  },
  {
    iso: "FM",
    countryName: "Micronesia, Federated States of",
    phoneCode: "691",
  },
  {
    iso: "FO",
    countryName: "Faroe Islands",
    phoneCode: "298",
  },
  { iso: "FR", countryName: "France", phoneCode: "33" },
  { iso: "GA", countryName: "Gabon", phoneCode: "241" },
  {
    iso: "GB",
    countryName: "United Kingdom of Great Britain and Northern Ireland",
    phoneCode: "44",
  },
  { iso: "GD", countryName: "Grenada", phoneCode: "1473" },
  { iso: "GE", countryName: "Georgia", phoneCode: "995" },
  {
    iso: "GF",
    countryName: "French Guiana",
    phoneCode: "594",
  },
  { iso: "GG", countryName: "Guernsey", phoneCode: "44" },
  { iso: "GH", countryName: "Ghana", phoneCode: "233" },
  {
    iso: "GI",
    countryName: "Gibraltar",
    phoneCode: "350",
  },
  {
    iso: "GL",
    countryName: "Greenland",
    phoneCode: "299",
  },
  { iso: "GM", countryName: "Gambia", phoneCode: "220" },
  { iso: "GN", countryName: "Guinea", phoneCode: "224" },
  {
    iso: "GP",
    countryName: "Guadeloupe",
    phoneCode: "590",
  },
  {
    iso: "GQ",
    countryName: "Equatorial Guinea",
    phoneCode: "240",
  },
  { iso: "GR", countryName: "Greece", phoneCode: "30" },
  {
    iso: "GS",
    countryName: "South Georgia and the South Sandwich Islands",
    phoneCode: "500",
  },
  {
    iso: "GT",
    countryName: "Guatemala",
    phoneCode: "502",
  },
  { iso: "GU", countryName: "Guam", phoneCode: "1671" },
  {
    iso: "GW",
    countryName: "Guinea-Bissau",
    phoneCode: "245",
  },
  { iso: "GY", countryName: "Guyana", phoneCode: "595" },
  {
    iso: "HK",
    countryName: "Hong Kong",
    phoneCode: "852",
  },
  { iso: "HN", countryName: "Honduras", phoneCode: "504" },
  { iso: "HR", countryName: "Croatia", phoneCode: "385" },
  { iso: "HT", countryName: "Haiti", phoneCode: "509" },
  { iso: "HU", countryName: "Hungary", phoneCode: "36" },
  {
    iso: "ID",
    countryName: "Indonesia",
    phoneCode: "62",
  },
  {
    iso: "IE",
    countryName: "Ireland",
    phoneCode: "353",
  },
  { iso: "IL", countryName: "Israel", phoneCode: "972" },
  {
    iso: "IM",
    countryName: "Isle of Man",
    phoneCode: "44",
  },
  { iso: "IN", countryName: "India", phoneCode: "91" },
  {
    iso: "IO",
    countryName: "British Indian Ocean Territory",
    phoneCode: "246",
  },
  { iso: "IQ", countryName: "Iraq", phoneCode: "964" },
  {
    iso: "IR",
    countryName: "Iran, Islamic Republic of",
    phoneCode: "98",
  },
  { iso: "IS", countryName: "Iceland", phoneCode: "354" },
  { iso: "IT", countryName: "Italy", phoneCode: "39" },
  { iso: "JE", countryName: "Jersey", phoneCode: "44" },
  { iso: "JM", countryName: "Jamaica", phoneCode: "1876" },
  { iso: "JO", countryName: "Jordan", phoneCode: "962" },
  { iso: "JP", countryName: "Japan", phoneCode: "81" },
  { iso: "KE", countryName: "Kenya", phoneCode: "254" },
  {
    iso: "KG",
    countryName: "Kyrgyzstan",
    phoneCode: "996",
  },
  { iso: "KH", countryName: "Cambodia", phoneCode: "855" },
  { iso: "KI", countryName: "Kiribati", phoneCode: "686" },
  { iso: "KM", countryName: "Comoros", phoneCode: "269" },
  {
    iso: "KN",
    countryName: "Saint Kitts and Nevis",
    phoneCode: "1869",
  },
  {
    iso: "KP",
    countryName: "Korea, Democratic People's Republic of",
    phoneCode: "850",
  },
  {
    iso: "KR",
    countryName: "Korea, Republic of",
    phoneCode: "82",
  },
  { iso: "KW", countryName: "Kuwait", phoneCode: "965" },
  {
    iso: "KY",
    countryName: "Cayman Islands",
    phoneCode: " 345",
  },
  {
    iso: "KZ",
    countryName: "Kazakhstan",
    phoneCode: "77",
  },
  {
    iso: "LA",
    countryName: "Lao People's Democratic Republic",
    phoneCode: "856",
  },
  { iso: "LB", countryName: "Lebanon", phoneCode: "961" },
  {
    iso: "LC",
    countryName: "Saint Lucia",
    phoneCode: "1758",
  },
  {
    iso: "LI",
    countryName: "Liechtenstein",
    phoneCode: "423",
  },
  { iso: "LK", countryName: "Sri Lanka", phoneCode: "94" },
  { iso: "LR", countryName: "Liberia", phoneCode: "231" },
  { iso: "LS", countryName: "Lesotho", phoneCode: "266" },
  {
    iso: "LT",
    countryName: "Lithuania",
    phoneCode: "370",
  },
  {
    iso: "LU",
    countryName: "Luxembourg",
    phoneCode: "352",
  },
  { iso: "LV", countryName: "Latvia", phoneCode: "371" },
  { iso: "LY", countryName: "Libya", phoneCode: "218" },
  { iso: "MA", countryName: "Morocco", phoneCode: "212" },
  { iso: "MC", countryName: "Monaco", phoneCode: "377" },
  {
    iso: "MD",
    countryName: "Moldova, Republic of",
    phoneCode: "373",
  },
  {
    iso: "ME",
    countryName: "Montenegro",
    phoneCode: "382",
  },
  {
    iso: "MF",
    countryName: "Saint Martin, (French part)",
    phoneCode: "590",
  },
  { iso: "MG", countryName: "Madagascar", phoneCode: "261" },
  {
    iso: "MH",
    countryName: "Marshall Islands",
    phoneCode: "692",
  },
  {
    iso: "MK",
    countryName: "North Macedonia",
    phoneCode: "389",
  },
  { iso: "ML", countryName: "Mali", phoneCode: "223" },
  { iso: "MM", countryName: "Myanmar", phoneCode: "95" },
  { iso: "MN", countryName: "Mongolia", phoneCode: "976" },
  { iso: "MO", countryName: "Macao", phoneCode: "853" },
  {
    iso: "MP",
    countryName: "Northern Mariana Islands",
    phoneCode: "1670",
  },
  {
    iso: "MQ",
    countryName: "Martinique",
    phoneCode: "596",
  },
  {
    iso: "MR",
    countryName: "Mauritania",
    phoneCode: "222",
  },
  {
    iso: "MS",
    countryName: "Montserrat",
    phoneCode: "1664",
  },
  { iso: "MT", countryName: "Malta", phoneCode: "356" },
  {
    iso: "MU",
    countryName: "Mauritius",
    phoneCode: "230",
  },
  {
    iso: "MV",
    countryName: "Maldives",
    phoneCode: "960",
  },
  { iso: "MW", countryName: "Malawi", phoneCode: "265" },
  { iso: "MX", countryName: "Mexico", phoneCode: "52" },
  { iso: "MY", countryName: "Malaysia", phoneCode: "60" },
  {
    iso: "MZ",
    countryName: "Mozambique",
    phoneCode: "258",
  },
  { iso: "NA", countryName: "Namibia", phoneCode: "264" },
  {
    iso: "NC",
    countryName: "New Caledonia",
    phoneCode: "687",
  },
  {
    iso: "NE",
    countryName: "Niger",
    phoneCode: "227",
  },
  {
    iso: "NF",
    countryName: "Norfolk Island",
    phoneCode: "672",
  },
  {
    iso: "NG",
    countryName: "Nigeria",
    phoneCode: "234",
  },
  {
    iso: "NI",
    countryName: "Nicaragua",
    phoneCode: "505",
  },
  { iso: "NL", countryName: "Netherlands", phoneCode: "31" },
  { iso: "NO", countryName: "Norway", phoneCode: "47" },
  { iso: "NP", countryName: "Nepal", phoneCode: "977" },
  { iso: "NR", countryName: "Nauru", phoneCode: "674" },
  {
    iso: "NU",
    countryName: "Niue",
    phoneCode: "683",
  },
  {
    iso: "NZ",
    countryName: "New Zealand",
    phoneCode: "64",
  },
  { iso: "OM", countryName: "Oman", phoneCode: "968" },
  { iso: "PA", countryName: "Panama", phoneCode: "507" },
  { iso: "PE", countryName: "Peru", phoneCode: "51" },
  {
    iso: "PF",
    countryName: "French Polynesia",
    phoneCode: "689",
  },
  {
    iso: "PG",
    countryName: "Papua New Guinea",
    phoneCode: "675",
  },
  {
    iso: "PH",
    countryName: "Philippines",
    phoneCode: "63",
  },
  { iso: "PK", countryName: "Pakistan", phoneCode: "92" },
  { iso: "PL", countryName: "Poland", phoneCode: "48" },
  {
    iso: "PM",
    countryName: "Saint Pierre and Miquelon",
    phoneCode: "508",
  },
  {
    iso: "PN",
    countryName: "Pitcairn",
    phoneCode: "872",
  },
  {
    iso: "PR",
    countryName: "Puerto Rico",
    phoneCode: "1939",
  },
  {
    iso: "PS",
    countryName: "Palestine, State of",
    phoneCode: "970",
  },
  { iso: "PT", countryName: "Portugal", phoneCode: "351" },
  { iso: "PW", countryName: "Palau", phoneCode: "680" },
  { iso: "PY", countryName: "Paraguay", phoneCode: "595" },
  { iso: "QA", countryName: "Qatar", phoneCode: "974" },
  { iso: "RE", countryName: "Réunion", phoneCode: "262" },
  { iso: "RO", countryName: "Romania", phoneCode: "40" },
  { iso: "RS", countryName: "Serbia", phoneCode: "381" },
  {
    iso: "RU",
    countryName: "Russian Federation",
    phoneCode: "7",
  },
  { iso: "RW", countryName: "Rwanda", phoneCode: "250" },
  {
    iso: "SA",
    countryName: "Saudi Arabia",
    phoneCode: "966",
  },
  {
    iso: "SB",
    countryName: "Solomon Islands",
    phoneCode: "677",
  },
  { iso: "SC", countryName: "Seychelles", phoneCode: "248" },
  { iso: "SD", countryName: "Sudan", phoneCode: "249" },
  { iso: "SE", countryName: "Sweden", phoneCode: "46" },
  { iso: "SG", countryName: "Singapore", phoneCode: "65" },
  {
    iso: "SH",
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    phoneCode: "290",
  },
  { iso: "SI", countryName: "Slovenia", phoneCode: "386" },
  {
    iso: "SJ",
    countryName: "Svalbard and Jan Mayen",
    phoneCode: "47",
  },
  { iso: "SK", countryName: "Slovakia", phoneCode: "421" },
  {
    iso: "SL",
    countryName: "Sierra Leone",
    phoneCode: "232",
  },
  {
    iso: "SM",
    countryName: "San Marino",
    phoneCode: "378",
  },
  { iso: "SN", countryName: "Senegal", phoneCode: "221" },
  { iso: "SO", countryName: "Somalia", phoneCode: "252" },
  { iso: "SR", countryName: "Suriname", phoneCode: "597" },
  {
    iso: "SS",
    countryName: "South Sudan",
    phoneCode: "211",
  },
  {
    iso: "ST",
    countryName: "Sao Tome and Principe",
    phoneCode: "239",
  },
  {
    iso: "SV",
    countryName: "El Salvador",
    phoneCode: "503",
  },
  {
    iso: "SY",
    countryName: "Syrian Arab Republic",
    phoneCode: "963",
  },
  {
    iso: "SZ",
    countryName: "Eswatini",
    phoneCode: "268",
  },
  {
    iso: "TC",
    countryName: "Turks and Caicos Islands",
    phoneCode: "1649",
  },
  { iso: "TD", countryName: "Chad", phoneCode: "235" },
  { iso: "TG", countryName: "Togo", phoneCode: "228" },
  { iso: "TH", countryName: "Thailand", phoneCode: "66" },
  {
    iso: "TJ",
    countryName: "Tajikistan",
    phoneCode: "992",
  },
  { iso: "TK", countryName: "Tokelau", phoneCode: "690" },
  {
    iso: "TL",
    countryName: "Timor-Leste",
    phoneCode: "670",
  },
  {
    iso: "TM",
    countryName: "Turkmenistan",
    phoneCode: "993",
  },
  { iso: "TN", countryName: "Tunisia", phoneCode: "216" },
  { iso: "TO", countryName: "Tonga", phoneCode: "676" },
  { iso: "TR", countryName: "Türkiye", phoneCode: "90" },
  {
    iso: "TT",
    countryName: "Trinidad and Tobago",
    phoneCode: "1868",
  },
  {
    iso: "TV",
    countryName: "Tuvalu",
    phoneCode: "688",
  },
  {
    iso: "TW",
    countryName: "Taiwan, Province of China",
    phoneCode: "886",
  },
  {
    iso: "TZ",
    countryName: "Tanzania, United Republic of",
    phoneCode: "255",
  },
  { iso: "UA", countryName: "Ukraine", phoneCode: "380" },
  { iso: "UG", countryName: "Uganda", phoneCode: "256" },
  {
    iso: "US",
    countryName: "United States of America",
    phoneCode: "1",
  },
  { iso: "UY", countryName: "Uruguay", phoneCode: "598" },
  {
    iso: "UZ",
    countryName: "Uzbekistan",
    phoneCode: "998",
  },
  {
    iso: "VA",
    countryName: "Holy See",
    phoneCode: "379",
  },
  {
    iso: "VC",
    countryName: "Saint Vincent and the Grenadines",
    phoneCode: "1784",
  },
  {
    iso: "VE",
    countryName: "Venezuela, Bolivarian Republic of",
    phoneCode: "58",
  },
  {
    iso: "VG",
    countryName: "Virgin Islands, British",
    phoneCode: "1284",
  },
  {
    iso: "VI",
    countryName: "Virgin Islands, U.S.",
    phoneCode: "1340",
  },
  { iso: "VN", countryName: "Viet Nam", phoneCode: "84" },
  { iso: "VU", countryName: "Vanuatu", phoneCode: "678" },
  {
    iso: "WF",
    countryName: "Wallis and Futuna",
    phoneCode: "681",
  },
  { iso: "WS", countryName: "Samoa", phoneCode: "685" },
  { iso: "YE", countryName: "Yemen", phoneCode: "967" },
  { iso: "YT", countryName: "Mayotte", phoneCode: "262" },
  {
    iso: "ZA",
    countryName: "South Africa",
    phoneCode: "27",
  },
  { iso: "ZM", countryName: "Zambia", phoneCode: "260" },
  { iso: "ZW", countryName: "Zimbabwe", phoneCode: "263" },
]
export const getCountries = (type: DropdownTypeEnum.COUNTRIES_ISO | DropdownTypeEnum.COUNTRIES_PHONE_CODE) => {
  return COUNTRIES.map(country => ({
    id: type === DropdownTypeEnum.COUNTRIES_ISO ? country.iso : country.phoneCode,
    value: type === DropdownTypeEnum.COUNTRIES_ISO ? country.iso : country.phoneCode,
    label: country.countryName
  }));
}

