export const AccountReceivablesRights = {
        "AR::Dashboard::R": { groups: [7], url: "" , ParentRightsId: 1 , DisplayOrder: 2 , IsNavigationItem: true},
        "AR::Control-File::R": { groups: [7], url: "accounts-receivable/control-file", IsNavigationItem: true },
        "AR::Control-File::RW": { groups: [7], url: "" },
        "AR::Customer-Maintenance::R": { groups: [7], url: "", IsNavigationItem: true },
        "AR::Customer-Master::R": { groups: [7], url: "accounts-receivable/customer-maintenance/customer-master-list", IsNavigationItem: true },
        "AR::Customer-Master::RW": { groups: [7], url: "accounts-receivable/customer-maintenance/customer-master-list/add-customer", IsNavigationItem: false },
        "AR::Customer-Master::Filter::R": { groups: [7], url: "" },
        "AR::Aged-Trial::R": { groups: [7], url: "accounts-receivable/customer-maintenance/aged-trial-balance", IsNavigationItem: true },
        "AR::Aged-Trial::RW": { groups: [7], url: "" },
        "AR::Aged-Trial::Filters::R": { groups: [7], url: "" },
        "AR::Salesman::R": { groups: [7], url: "accounts-receivable/customer-maintenance/salesman", IsNavigationItem: true },
        "AR::Salesman::RW": { groups: [7], url: "" },
        "AR::Salesman::Filter::R": { groups: [7], url: "" },
        "AR::Salesman::Default-Salesman::R": { groups: [7], url: "accounts-receivable/customer-maintenance/salesman/default-salesman", IsNavigationItem: false },
        "AR::Salesman::Default-Salesman::CompanyNo::R": { groups: [7], url: "" },
        "AR::Salesman::Default-Salesman::RW": { groups: [7], url: "" },
        "AR::Salesman::Export::R": { groups: [7], url: "" },
        "AR::CSR-Maintenance::R": { groups: [7], url: "accounts-receivable/customer-maintenance/csr-maintenance", IsNavigationItem: true },
        "AR::CSR-Maintenance::RW": { groups: [7], url: "" },
        "AR::CSR-Maintenance::Filter::R": { groups: [7], url: "" },
        "AR::CSR-Maintenance::ExportList::R": { groups: [7], url: "" },
        "AR::Credit-Limit::R": { groups: [7], url: "", IsNavigationItem: true },
        "AR::Credit-Limit-Groupings::R": { groups: [7], url: "accounts-receivable/credit-limit/credit-limit-groupings", IsNavigationItem: true },
        "AR::Credit-Limit-Groupings::RW": { groups: [7], url: "" },
        "AR::Credit-Limit-Groupings::Filter::R": { groups: [7], url: "" },
        "AR::Credit-Limit-Grouping-Report::R": { groups: [7], url: "accounts-receivable/credit-limit/credit-limit-grouping-report", IsNavigationItem: true },
        "AR::Credit-Limit-Grouping-Report::RW": { groups: [7], url: "" },
        "AR::Credit-Limit-Grouping-Report::Filter::R": { groups: [7], url: "" },
        "AR::Credit-Limit-Auth::R": { groups: [7], url: "accounts-receivable/credit-limit/credit-limit-auth", IsNavigationItem: true },
        "AR::Credit-Limit-Auth::RW": { groups: [7], url: "" },
        "AR::Credit-Limit-Auth::Filter::R": { groups: [7], url: "" },
        "AR::Authorize-Over-Credit-Limit::R": { groups: [7], url: "accounts-receivable/credit-limit/authorize-over-credit-limit", IsNavigationItem: true },
        "AR::Authorize-Over-Credit-Limit::RW": { groups: [7], url: "" },
        "AR::AR-Invoices::R": { groups: [7], url: "", IsNavigationItem: true},
        "AR::Invoice-Inquiry::R": { groups: [7], url: "accounts-receivable/ar-invoices/invoice-inquiry", IsNavigationItem: true },
        "AR::Invoice-Inquiry::Filter::R": { groups: [7], url: "" },
        "AR::Invoice-History-Inquiry::R": { groups: [7], url: "accounts-receivable/ar-invoices/invoice-history-inquiry", IsNavigationItem: true },
        "AR::Invoice-History-Inquiry::Filter::R": { groups: [7], url: "" },
        "AR::Mobility-Statements::R": { groups: [7], url: "accounts-receivable/ar-invoices/mobility-statements", IsNavigationItem: true },
        "AR::Mobility-Statements::Filter::R": { groups: [7], url: "" },
        "AR::Monthly-Statements::RW": { groups: [7], url: "" },
        "AR::Cash-Receipts::R": { groups: [7], url: "accounts-receivable/cash-receipts", IsNavigationItem: true },
        "AR::Reports::R": { groups: [7], url: "accounts-receivable/ar-reports", IsNavigationItem: true },
        "AR::Reports::RW": { groups: [7], url: "" }
}