export const AccountPayablesRights = {
    "AP:Dashboard::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable" },
    "Ap::VM::Voucher-Entry::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management" },
    "Ap::VM::Voucher-Entry::Normal::RW": { groups: [1, 2, 3], url: "accounts-payable/voucher-management/voucher-entry/normal/create-new-entry" },
    "Ap::VM::Voucher-Entry::Normal::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management/voucher-entry/normal" },
    "Ap::VM::Voucher-Entry::Normal::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::Normal::PostPurchaseJournal::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VM::Voucher-Entry::Normal::NewEntry:Vendor::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VM::Voucher-Entry::LMS::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management/voucher-entry/arglms" },
    "Ap::VM::Voucher-Entry::LMS::FreightInvoice::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::LMS::FreightInvoice::CreateBatch:R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::LMS::FreightInvoice::CreateBatch:RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::VM::Voucher-Entry::LMS::ReviewBatch::RW": { groups: [1, 2, 3, 5], url: "accounts-payable/voucher-management/voucher-entry/arglms/create-new-entry" },
    "Ap::VM::Voucher-Entry::LMS::ReviewBatch::PostPurchaseJournal::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::VM::Voucher-Entry::LMS::RB::PostPurchaseJournal::JournalDate:R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::LMS::RB::PostPurchaseJournal::CashDisburseDate:R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::Paper::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management/voucher-entry/paper" },
    "Ap::VM::Voucher-Entry::Paper::FreightInvoice::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::Paper::FreightInvoice::CreateBatch:R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::Paper::FreightInvoice::CreateBatch:RW": { groups: [1, 2, 3, 5], url: "accounts-payable/voucher-management/voucher-entry/paper/create-new-entry" },
    "Ap::VM::Voucher-Entry::Paper::ReviewBatch::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::Voucher-Entry::Paper::ReviewBatch::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::VM::Voucher-Entry::Flexi::ReviewBatch::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::VM::Voucher-Entry::Flexi::ReviewBatch::PostPurchaseJournal::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VM::Voucher-Entry::Flexi::R": { groups: [1, 2, 3, 4], url: "accounts-payable/voucher-management/voucher-entry/flexi" },
    "Ap::VM::Voucher-Entry::Flexi::RW": { groups: [1, 2, 3], url: "accounts-payable/voucher-management/voucher-entry/flexi/create-new-entry" },
    "Ap::VM::Voucher-Entry::Flexi::UploadCSV::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::VM::Voucher-Entry::Flexi::UploadCSV::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VM::Voucher-Entry::Flexi::UploadCSV::DownloadTemplate::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::VM::Voucher-Entry::Flexi::PostPurchaseJournal::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VM::Voucher-Entry::Sogas::R": { groups: [1, 2, 3, 4], url: "accounts-payable/voucher-management/voucher-entry/sogas" },
    "Ap::VM::Voucher-Entry::Sogas::RW": { groups: [1, 2, 3], url: "accounts-payable/voucher-management/voucher-entry/sogas/create-new-entry" },
    "Ap::VM::Voucher-Entry::Sogas::select::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::VM::Voucher-Entry::Sogas::processType::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::VM::Voucher-Entry::Sogas::UploadCSV::DownloadTemplate::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::VM::Voucher-Entry::Sogas::PostPurchaseJournal::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VM::PurchaseJournal::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management/purchase-journal" },
    "AP::VM::PurchaseJournal::Filters::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management/check-inquiry" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::Vendor::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::InvoiceNo::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::StartDate::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::CheckNo::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::CheckHistory::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::CheckHistory::CheckDetails::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management/check-inquiry/check-details/:checkNo" },
    "Ap::VM::CheckInquiry::CheckPaymentHistory::VoucherDetails::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::VoucherMaintenance::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/voucher-management/voucher-maintenance" },
    "Ap::VM::VoucherMaintenance::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VM::VoucherMaintenance::VoucherType::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::VoucherMaintenance::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::VoucherMaintenance::VendorNo::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::VoucherMaintenance::StartDate::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VM::VoucherMaintenance::InvoiceNo::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::OP::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/open-payables" },
    "Ap::OP::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::OP::OPFilters::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::OP::ReportDate::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::OP::ReportType::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::OP::FileName::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::OP::OPFilters::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::VM::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::EE::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/employee-expenses-export" },
    "Ap::EE::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::EE::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::EE::BankGLNo::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::EE::DateToPay::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorMaintenance::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/vendor-management/vendor-maintenance" },
    "Ap::VNMT::VendorMaintenance::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorMaintenance::Vendor::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorMaintenance::Type::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorMaintenance::RW": { groups: [1, 2, 3], url: "accounts-payable/vendor-management/vendor-maintenance/add-vendor" },
    "Ap::VNMT::VendorMaintenance::EditVendor::RW": { groups: [1, 2, 3], url: "accounts-payable/vendor-management/vendor-maintenance/edit-vendor/:vendorNo" },
    "Ap::VNMT::VendorMaintenance::Status::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorMaintenance::Status::RW": { groups: [1, 2, 3], url: "" },
    "Ap::VNMT::VendorOwnerMapping::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/vendor-management/vendor-owner-mapping" },
    "Ap::VNMT::VendorOwnerMapping::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorOwnerMapping::Vendor::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorOwnerMapping::OwnerNo::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorOwnerMapping::Status::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::VNMT::VendorOwnerMappings::RW": { groups: [1, 2, 3], url: "" },
    "AP::PC::R": { groups: [1, 2, 3, 4], url: "accounts-payable/payment-cycle" },
    "Ap::PC::PaymentSelection::Company::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::VoucherToPay::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::StartingCheck::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::CheckDate::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::DateToPay::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::BankGLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::BankGLDesc::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::ForcedDiscount::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::RW": { groups: [1, 2, 3], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::VendorNumber::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::VoucherNumber::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::PartialPayAmount::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::OverrideDiscountAmount::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::ForceDiscount::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::PayHold::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::SingleCheck::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::MakePrepaid::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::PrepaidCheckNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PaymentSelection::AddPayment::CheckDate::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::CashRequirement::RW": { groups: [1, 2, 3], url: "" },
    "Ap::PC::CashRequirement::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::ApCheck::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::ApCheck::RW": { groups: [1, 2, 3], url: "" },
    "Ap::PC::PrintCheck::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::PrintCheck::RW": { groups: [1, 2, 3], url: "" },
    "Ap::PC::ClearChecks::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::PC::ClearChecks::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::CC::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/clear-checks" },
    "Ap::CC::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::CC::AddCheck::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::CC::AddCheck::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::CC::UploadCSV::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::CC::UploadCSV::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::CC::DownloadTemplate::RW": { groups: [1, 2, 3], url: "" },
    "Ap::CC::AddCheck::CheckNumber::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::CC::AddCheck::ClearDate::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::CC::AddCheck::ClearAmount::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APMT::R": { groups: [1, 2, 3, 4], url: "accounts-payable/ap-maintenance" },
    "Ap::APMT::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APMT::Company::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::CompanyName::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::ApGLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::BankGLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::DiscountsGLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::IntercoGLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::NextPJJRNLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::NextCDJRNLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::NextCheckNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::NextEntryNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::NextVoucherNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::PreEdChks::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::JobCostAct::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::RetentionGLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::PoActive::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::EmployeeExpenseGLNo::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::NextEEJRNL::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APMT::Filler::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APRPTMU::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/ap-reports" },
    "Ap::APRPTMU::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APRPTMU::ReportDate::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APRPTMU::ReportType::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APRPTMU::Filters::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APRPTMU::Filters::RW": { groups: [1, 2, 3, 5], url: "" },
    "Ap::APPDED::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APPDED::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APPDED::VendorMonth::R": { groups: [1, 2, 3, 4, 5], url: "accounts-payable/ap-period/vendor-month-year-end-process" },
    "Ap::APPDED::VendorMonth::Company::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APPDED::VendorMonth::SaveCopy::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APPDED::VendorMonth::ClearYear::R": { groups: [1, 2, 3, 4, 5], url: "" },
    "Ap::APPDED::VendorFileMaintenance:::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APPDED::VendorFileMaintenance::R": { groups: [1, 2, 3, 4], url: "accounts-payable/ap-period/vendor-file-maintenance-1099" },
    "Ap::APPDED::VendorFileMaintenance::Year::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::R": { groups: [1, 2, 3, 4], url: "accounts-payable/ap-period/year-end-1099-process-menu" },
    "Ap::APPDED::YearEnd1099Process::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APPDED::YearEnd1099Process::Restart::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::Options::ReportYear::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::Options::FormType::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::Options::PaymentsReportYear::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::Create1099File::ExcessAmount::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::Create1099File::ExcessAmount::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APPDED::YearEnd1099Process::ReviewFiles::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::ReviewFiles::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APPDED::YearEnd1099Process::PrintCheck::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::PrintCheck::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APPDED::YearEnd1099Process::TestPrint::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::Update1099File::R": { groups: [1, 2, 3, 4], url: "accounts-payable/ap-period/update-1099-file" },
    "Ap::APPDED::Update1099File::RW": { groups: [1, 2, 3], url: "" },
    "Ap::APPDED::Update1099File::RecordType::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::Ctl::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::APPDED::YearEnd1099Process::tin::R": { groups: [1, 2, 3, 4], url: "" },
    "Ap::AuthGenrate::R": { groups: [1, 2], url: "accounts-payable/auth-generate" },
    "Ap::AuthGenrate::RW": { groups: [1, 2], url: "" },
}