export class CarrierInvoiceHeaderEntity {
  constructor(
    public readonly isDeleted: string,
    public readonly companyNo: number,
    public readonly carrierId: string,
    public readonly carrierInvoiceNumber: string,
    public readonly invoiceType: string,
    public readonly invoiceDate: number,
    public readonly invoiceAmount: number,
    public readonly orderNumber: number,
    public readonly shippingReferenceNumber: number,
    public readonly dateTimeStamp: string,
    public readonly carrierInvoiceStatus: string,
    public readonly orderOverrideTotal: number,
    public readonly filler1: string,
    public readonly approvalStatus: string,
    public readonly approvalDateTime: string,
    public readonly apInvoiceStatus: string,
    public readonly apDateTime: string,
    public readonly carrierUserId: string,
    public readonly billingType: string,
    public readonly carrierIpAddress: string,
    public readonly vendorNo: string,
    public readonly checkNumber: number,
    public readonly checkDate: number,
    public readonly voucherAmount: number,
    public readonly filler2: string,
  ) {}
}
