export class CheckInquiryEntity {
    constructor(
        public isDeleted: string,
        public companyNo: number,
        public vendorNo: number,
        public voucherNo: number,
        public header: number,
        public sequenceNo: number,
        public grossAmount: number,
        public discount: number,
        public partialPaidToDate: number,
        public invoiceDescription: string,
        public apGLAccountNo: number,
        public retentionVoucher: string,
        public discountDueDate: number,
        public invoiceDate: number,
        public dueDate: number,
        public checkNo: number,
        public prepaidVoucher: string,
        public lastPaidDate: number,
        public cashDisbursedDate: number,
        public purchaseJournalDate: number,
        public purchaseJournalNo: string,
        public heldPaymentVoucher: string,
        public heldDescription: string,
        public singleCheck: string,
        public bankGLNo: number,
        public paidAmount: number,
        public discountTaken: number,
        public invoiceNo: string,
    ) { }
}
