export class GeneralSystemEntity {
  constructor(
    public isDeleted: string,
    public tableType: string,
    public tableCode: string,
    public tableDesc: string,
    public netDays: number,
    public proxDays: number,
    public discount: number,
    public rackPriceAddOn: number,
    public discountDays: number,
    public priceListGroup: number,
    public priceListColumn: number,
    public groupHeading: string,
    public columnHeading: string,
    public productGroupCode: string,
    public customerRankingColumnNo: number,
    public rackColumn: number,
    public inventoryColumn: number,
    public shippingDescription: string,
    public productClassCode: string,
    public salesmanType: string,
    public specialMsgDKG: string,
    public stdApiGravity: number,
    public inventoryGroupCode: string,
    public salesGlNo: number,
    public shortDescription: string,
    public sellProduct: string,
    public inventoryCompSeq: number,
    public defaultAltProductDesc: string,
    public inventoryCompSort: number,
    public containerTypeBP: string,
    public freightTableCode: string,
    public termPt2NetDays: number,
    public termPt3NetDays: number,
    public termsPart1Pct: number,
    public termsPart2Pct: number,
    public termsPart3Pct: number,
    public unitTypeBBlnd: string,
    public secondDescription: string,
    public einNumber: number,
    public vcfCode: string,
    public fluidCode: string,
    public terminalIoCode: string,
    public codeLength: number,
    public alphaNumeric: string,
  ) {}
}
